function [properties] = calculateEccentricity(BW_in)
% Auto-generated by imageRegionAnalyzer app on 19-Dec-2024
properties = regionprops('table', BW_in, {'Area', 'Eccentricity'});
[~, maxInd] = max(properties.Area);
properties = properties{maxInd, 2};
end